
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

# --- FRONTEND (URL DE PRODUCCIÓN) ---
# Aquí pondrás la URL de tu frontend en Vercel o Railway
frontend.url=${FRONTEND_URL}

# --- HIBERNATE ---
# 'update' es seguro para portafolios, asegura que tus tablas nuevas se creen
spring.jpa.hibernate.ddl-auto=update